#!/bin/bash

set -e

[ -z "$SRC" ] && SRC="$1"
[ -z "$DST" ] && DST="$2"

echo "SRC=$SRC"
echo "DST=$DST"

ip link set "$SRC" down
ip link set "$SRC" name "$DST" || ip link set "$SRC" up
ip link set "$DST" up

