#!/bin/bash

set -e

[ -z "$SRC" ] && SRC="$1"
[ -z "$DST" ] && DST="$2"

echo "SRC=$SRC"
echo "DST=$DST"

DSTMAXLEN=14
if [ ${#DST} -ge $DSTMAXLEN ]; then
 echo "error: expect [$DST] to be less than $DSTMAXLEN bytes."
 exit 1
fi

ip link set "$SRC" down
ip link set "$SRC" name "$DST" || ip link set "$SRC" up
ip link set "$DST" up

